### ISSUE TITLE
Minimum Node requirement became >=18.0.0

### ISSUE THREAD

**Issue by sevilyilmaz** [bahmutov/find-cypress-specs#240]
I started getting build errors after upgrading `cypress-split` to `1.20.1`. I found out that this package started using `tsx` with [this commit](https://github.com/bahmutov/find-cypress-specs/commit/1e669c9cb2545b6cc9cc3ca907490012af1dae12) which has a Node 18 requirement. The error that I get:

```
error tsx@4.7.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.16.0"
```

Since this change is a breaking one it would be good to mention in the docs or somewhere relevant.

**Comment by bahmutov** [comment]
The dependencies and tracking minimum Node version is broken in general. I will update.

**Comment by bahmutov** [comment]
done
