### ISSUE TITLE
Find specs dependent on changed files

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/find-cypress-specs#40]
Imagine we have several spec files and several files with utilities imported and used by the specs

```
cypress/
  integration/
    spec.js
    utils.js
```
```js
// file spec.js
import {foo} from './utils'
```

If we modify the `utils.js` it would be nice to run the spec files possibly affected by the change, such as `spec.js`. Right now we skip this because we only find `utils.js` changed file, and it is not a spec, so nothing to run first...

**Comment by mudit94** [comment]
+1 for the above feature request

**Comment by bahmutov** [comment]
Will try implement using https://github.com/bahmutov/spec-change
