### ISSUE TITLE
Update for Cypress 10 needed

### ISSUE THREAD

**Issue by borecz** [bahmutov/find-cypress-specs#44]
Hi @bahmutov,
thanks for this beautiful plugin and all the other contributions! :)

Could you please update to support latest Cypress 10? 

Thanks in advance.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/57007154/175615703-249154d7-f7ed-4138-87b0-49855145ed14.png">

**Comment by bahmutov** [comment]
It is more complicated, I hope to update it of course but not right now. If you have some time try to open a pull request to implement this
