### ISSUE TITLE
Package is not working with typescript cypress.config file on Cypress 10

### ISSUE THREAD

**Issue by Truput** [bahmutov/find-cypress-specs#47]
Currently, on our project, we are using cypress.config.ts file, but when we try to use this package, we have the following error:
`Error: Cannot find module '/__w/projectName/projectName/cypress.config.js'
Require stack:
- /usr/local/lib/node_modules/find-cypress-specs/node_modules/require-and-forget/src/index.js
- /usr/local/lib/node_modules/find-cypress-specs/src/index.js
- /usr/local/lib/node_modules/find-cypress-specs/bin/find.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireAndForget (/usr/local/lib/node_modules/find-cypress-specs/node_modules/require-and-forget/src/index.js:25:15)
    at getConfigJs (/usr/local/lib/node_modules/find-cypress-specs/src/index.js:[30](linkToTheRun):25)
    at getConfig (/usr/local/lib/node_modules/find-cypress-specs/src/index.js:38:10)
    at getSpecs (/usr/local/lib/node_modules/find-cypress-specs/src/index.js:133:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/find-cypress-specs/bin/find.js:38:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:[32](linkToTheRun:33)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/find-cypress-specs/node_modules/require-and-forget/src/index.js',
    '/usr/local/lib/node_modules/find-cypress-specs/src/index.js',
    '/usr/local/lib/node_modules/find-cypress-specs/bin/find.js'`
It would be really great, if typescript config files support were added.

**Comment by haipinggong** [comment]
@bahmutov , is this going to be supported by adding a new command line argument, e.g. --config?

**Comment by bahmutov** [comment]
No, it is a problem of loading the cypress.config.ts to "execute" it once, not the problem of finding it

**Comment by mtafseerhaider** [comment]
is there any workaround?

**Comment by bahmutov** [comment]
:) I don’t think so unfortunately

**Comment by Truput** [comment]
> is there any workaround?

You can create the second config-file, just us with some basic configuration and run all your tests with config-file cli flag. There will be no conflicts and the package will work just fine. We use such workaround on our project now

**Comment by cullylarson** [comment]
Could you accept the config itself as an argument, and then leave it up to the caller to read the config appropriately? Or maybe just accept `specPattern` and `excludeSpecPattern` as arguments in place of reading the config?

**Comment by actionJacksonfv** [comment]
Any updates on with working with .ts files?

**Comment by bahmutov** [comment]
Not yet, no one has opened a PR :(

**Comment by haipinggong** [comment]
@bahmutov , last time you mentioned that the issue is loading the cypress.config.ts to "execute" it once. I tried to make a copy of .ts file and looks like it works. And I still feel that we should have a way for the user to specify which config file to use since user may have multiple config files or in a different folder instead of root level. Please let me know if you have any objection or not.

**Comment by bahmutov** [comment]
I’m not sure what you mean by “make a copy and it works”

**Comment by haipinggong** [comment]
@bahmutov , you are right. My code does not work when it is using export default, I have closed my PR.

**Comment by bahmutov** [comment]
Yeah, loading TS or even finding which config to find is unsupported right now
